### ISSUE TITLE
Firefox and Chrome usage last updated 3 months ago

### ISSUE THREAD

**Issue by nicolae-stroncea** [ActivityWatch/stats#3]
Tracking Firefox and Chrome usage is a great idea and a good metric for how many people actually use ActivityWatch.

I noticed the data has been stale over the past 3 months. Is it still being recorded somewhere?

**Comment by johan-bjareholt** [comment]
Daily usage of firefox extension is right now at 907 users (44% Linux, 43% Windows, 12% macOS)

Daily usage of chrome extension si right now at 1700 users this week (1000 users on windows, 390 on linux and 324 on macOS)

Where is the is the public data for this that was last updated 3 months ago? Can't find it.

**Comment by ErikBjare** [comment]
@johan-bjareholt I've manually placed it here: https://github.com/ActivityWatch/stats/tree/master/data

Chrome Webstore and Mozilla Addons collect "active users" stats for us, but the process to add them to this repo is manual (no easy way to automate). I'm intending to update them at least once a year (because the Firefox stats are only saved for 365 days), and might not do it much more often than so since it's quite fiddly.

If you have a specific query about if something has recently changed, feel free to ping @johan-bjareholt or me and ask :)

**Comment by nicolae-stroncea** [comment]
@ErikBjare  that makes sense. I was originally thinking that there was some sort of Github Action/script you were running to execute it, and that it malfunctioned. Would be interesting to see how the pandemic has influenced rate of AW usage, but it's not a priority :)

Closing
